name: Create release

# Controls when the action will run
# Option bellow allows you to run the workflow manually
on:
  workflow_dispatch:

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup git config
        run: |
           git config user.name "GitHub Actions Bot"
           git config user.email "<>"

      # Run release task
      - name: Release with Gradle Release Plugin
        run: ./gradlew release
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
